"""
Django settings for FregatMonitoring project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y+w2ww$#!c-s)gm2d@77q9h0(j34kq6%w^)64ahh^(ui7(035p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "frgs005x", "192.168.88.238", "frgv006a", "192.168.88.234", "frgv008a", 'frgv008a.fregat.local', 'frgv006a.fregat.local', '10.112.1.2', '10.112.1.234']

LOGIN_URL = 'FregatMonitoringApp:login'

# Application definition

INSTALLED_APPS = [
    'FregatMonitoringApp.apps.FregatmonitoringappConfig',
    'SPR.apps.SprConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'FregatMonitoring.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'FregatMonitoring.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'production_fx': {
        'ENGINE': 'sql_server.pyodbc',
        'HOST': "FRGV202X\PRODUCTION",
        'USER': "Operator", #Operator, ProdReader
        'PASSWORD': "fregat", #fregat, 123
        'NAME': "FX_Hist",
        'PORT': "",
        'OPTIONS': {
            'driver': 'SQL Server Native Client 11.0'
        }
    },
    'zebra': {
        'ENGINE': 'sql_server.pyodbc',
        'HOST': "FRGV202X\PRODUCTION",
        'USER': "Zebra", #ZebraReader
        'PASSWORD': "123456", #123456
        'NAME': "ZebraNew",
        'PORT': "",
        'OPTIONS': {
            'driver': 'SQL Server Native Client 11.0'
        }
    },
    'SPR': {
        'ENGINE': 'sql_server.pyodbc',
        'HOST': "FRGV202X\PRODUCTION",
        'USER': "Operator",
        'PASSWORD': "fregat",
        'NAME': "SPR",
        'PORT': "",
        'OPTIONS': {
            'driver': 'SQL Server Native Client 11.0'
        }
    }
}

DATABASE_ROUTERS = ['SPR.routers.SPRRouter', 'FregatMonitoringApp.routers.FregatMonitoringAppRouter']


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
