# Generated by Django 3.2.10 on 2025-07-29 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SPR', '0002_locations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='locations',
            options={},
        ),
    ]
