# Generated by Django 3.2.10 on 2025-08-01 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SPR', '0003_auto_20250729_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='equipment',
            name='location_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SPR.locations'),
        ),
        migrations.AddField(
            model_name='locations',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(default='Другое', max_length=100),
        ),
        migrations.AlterField(
            model_name='locations',
            name='name',
            field=models.CharField(default='Другое', max_length=100),
        ),
        migrations.AlterModelTable(
            name='equipment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='locations',
            table=None,
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Другое', max_length=100)),
                ('equipment_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SPR.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Другое', max_length=100)),
                ('section_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SPR.sections')),
            ],
        ),
    ]
