# Generated by Django 3.2.10 on 2025-08-13 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SPR', '0004_auto_20250801_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Другое', max_length=100)),
            ],
            options={
                'db_table': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Staff_positions',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Другое', max_length=100)),
                ('service', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SPR.services')),
            ],
            options={
                'db_table': 'Staff_positions',
            },
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='nodes',
            old_name='section_id',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='sections',
            old_name='equipment_id',
            new_name='equipment',
        ),
        migrations.AlterModelTable(
            name='equipment',
            table='Equipment',
        ),
        migrations.AlterModelTable(
            name='locations',
            table='Locations',
        ),
        migrations.AlterModelTable(
            name='nodes',
            table='Nodes',
        ),
        migrations.AlterModelTable(
            name='sections',
            table='Sections',
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('operation_content', models.TextField()),
                ('tools', models.TextField(null=True)),
                ('time_min', models.IntegerField(null=True)),
                ('periodicity_days', models.IntegerField(null=True)),
                ('risk', models.CharField(max_length=10, null=True)),
                ('last_service', models.DateField(null=True)),
                ('next_service', models.DateField(null=True)),
                ('node', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SPR.nodes')),
                ('staff_position', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SPR.staff_positions')),
            ],
            options={
                'db_table': 'Repair_operations',
            },
        ),
        migrations.CreateModel(
            name='Repair_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SPR.works')),
            ],
            options={
                'db_table': 'Repair_schedule',
            },
        ),
    ]
