# Generated by Django 3.2.10 on 2025-08-20 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SPR', '0006_auto_20250813_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repair_staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('surname', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='equipment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='locations',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sections',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='services',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff_positions',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='works',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Scheduled_operations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(null=True)),
                ('finish_date', models.DateField(null=True)),
                ('current_status', models.IntegerField(default=0)),
                ('comment', models.TextField(null=True)),
                ('elapsed_time_min', models.IntegerField(null=True)),
                ('start_timestamp', models.DateTimeField(null=True)),
                ('finish_timestamp', models.DateTimeField(null=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SPR.works')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='SPR.repair_staff')),
            ],
            options={
                'db_table': 'Scheduled_operations',
            },
        ),
        migrations.AddField(
            model_name='repair_staff',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SPR.staff_positions'),
        ),
    ]
