# Generated by Django 3.2.10 on 2025-08-28 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SPR', '0007_auto_20250820_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repair_schedule_fact',
            fields=[
                ('operation', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SPR.works')),
                ('_1', models.IntegerField(default=0)),
                ('_2', models.IntegerField(default=0)),
                ('_3', models.IntegerField(default=0)),
                ('_4', models.IntegerField(default=0)),
                ('_5', models.IntegerField(default=0)),
                ('_6', models.IntegerField(default=0)),
                ('_7', models.IntegerField(default=0)),
                ('_8', models.IntegerField(default=0)),
                ('_9', models.IntegerField(default=0)),
                ('_10', models.IntegerField(default=0)),
                ('_11', models.IntegerField(default=0)),
                ('_12', models.IntegerField(default=0)),
                ('_13', models.IntegerField(default=0)),
                ('_14', models.IntegerField(default=0)),
                ('_15', models.IntegerField(default=0)),
                ('_16', models.IntegerField(default=0)),
                ('_17', models.IntegerField(default=0)),
                ('_18', models.IntegerField(default=0)),
                ('_19', models.IntegerField(default=0)),
                ('_20', models.IntegerField(default=0)),
                ('_21', models.IntegerField(default=0)),
                ('_22', models.IntegerField(default=0)),
                ('_23', models.IntegerField(default=0)),
                ('_24', models.IntegerField(default=0)),
                ('_25', models.IntegerField(default=0)),
                ('_26', models.IntegerField(default=0)),
                ('_27', models.IntegerField(default=0)),
                ('_28', models.IntegerField(default=0)),
                ('_29', models.IntegerField(default=0)),
                ('_30', models.IntegerField(default=0)),
                ('_31', models.IntegerField(default=0)),
                ('_32', models.IntegerField(default=0)),
                ('_33', models.IntegerField(default=0)),
                ('_34', models.IntegerField(default=0)),
                ('_35', models.IntegerField(default=0)),
                ('_36', models.IntegerField(default=0)),
                ('_37', models.IntegerField(default=0)),
                ('_38', models.IntegerField(default=0)),
                ('_39', models.IntegerField(default=0)),
                ('_40', models.IntegerField(default=0)),
                ('_41', models.IntegerField(default=0)),
                ('_42', models.IntegerField(default=0)),
                ('_43', models.IntegerField(default=0)),
                ('_44', models.IntegerField(default=0)),
                ('_45', models.IntegerField(default=0)),
                ('_46', models.IntegerField(default=0)),
                ('_47', models.IntegerField(default=0)),
                ('_48', models.IntegerField(default=0)),
                ('_49', models.IntegerField(default=0)),
                ('_50', models.IntegerField(default=0)),
                ('_51', models.IntegerField(default=0)),
                ('_52', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Fact_repair_schedule',
            },
        ),
        migrations.AlterModelOptions(
            name='repair_staff',
            options={'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Служба', 'verbose_name_plural': 'Службы'},
        ),
        migrations.AlterModelOptions(
            name='staff_positions',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AddField(
            model_name='repair_staff',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repair_schedule',
            name='operation',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SPR.works'),
        ),
        migrations.AlterModelTable(
            name='repair_staff',
            table='Repair_staff',
        ),
    ]
